KNOWN_TEAMS = [
    "Crvena Zvezda", "Partizan", "Lietkabelis", "Jonava",
    "Legia", "Lublin", "Buducnost", "Podgorica",
    "Dep. San Jose", "Colonias Gold", "Batang Kankaloo",
    "Marikina Verdiamonds", "Pasay Voyagers", "Davao Tigers",
    "Puerto Rico U16 W", "Argentina U16 W", "Venezuela U16 W",
    "USA U16 W", "Blumenau APAB", "Joacaba", "San Miguel Beermen",
    "Converge FiberXers", "Rajawali Medan", "Bima Perkasa Yogyakarta",
    "Binan Tatak Gel", "Davao Tigers", "Al Ahli Tripoli", "APR",
    "Al-Ahli Dubai", "Taoyuan Pauian Pilots", "Ironi Eilat", "Maccabi Rishon",
    "Great Britain W", "Lithuania W", "Nelson Giants", "Bay Hawks",
    "Saskatchewan Rattlers", "Scarborough Shooting Stars",
    "Townsville Flames W", "Southern District Spartans W",
    "Phoenix Fuelmasters", "Blackwater Bossing",
    "Lakeside Lightning W", "Cockburn Cougars W",
    "Perth Redbacks W", "Kalamunda Eastern Suns W",
    "Rockingham Flames W", "South West Slammers W",
    "Townsville Heat", "Southern District",
    "Zhejiang Guangsha", "Al-Riyadi Beirut",
    "San Miguel Beermen", "Fuel Masters",
    "Hotshots", "Rain or Shine Elasto Painters",
    "Barangay Ginebra San Miguel", "Da Nang Dragons",
    "Ho Chi Minh City Wings", "Satria Muda Pertamina",
    "Prawira Bandung", "SESI Araraquara W",
    "Sampaio W", "Adelitas Women", "Freseras Irapuato Women",
    "Fuerza Regia Women", "Abejas de Leon Women",
    "Panteras Aguascalientes Women", "El Calor Women"
]